markdown: pandoc
pandoc:
    flags: '--csl=apa.csl --bibliography=ref.bib --smart -V lang=es'
    outputs:
        - markdown
        - mediawiki
        - pdf
        - epub
        - rst

destination: /srv/http/endefensadelsl.org

permalink: ":title.html"

lsi: false

