pandoc:
    extensions:
        - smart
        - html5
        - csl: 'apa.csl'
        - bibliography: 'ref.bib'
    flags: '--csl=apa.csl --bibliography=ref.bib'
    outputs: 
        - epub
        - rst
        - mediawiki
        - pdf

destination: /srv/http/endefensadelsl.org

permalink: ":title.html"

lsi: false

