markdown: pandoc
pandoc:
    skip: true
    flags: '--csl=apa.csl --bibliography=ref.bib --smart -V lang=es'
    outputs:
        - pdf: '--latex-engine=xelatex'
        - epub
        - markdown
        - mediawiki
        - rst

destination: /srv/http/endefensadelsl.org

permalink: ":title.html"

lsi: false

